import cron from"node-cron";import mongoose from"mongoose";import{reminderType}from"./lib/reminders.mjs";import{decryptSecret}from"./lib/secret.mjs";
const schema=collection=>new mongoose.Schema({},{strict:false,collection}),Tenant=mongoose.model("WorkerTenant",schema("tenants")),Student=mongoose.model("WorkerStudent",schema("students")),Fee=mongoose.model("WorkerFee",schema("feerecords")),DevMessage=mongoose.model("WorkerDevMessage",schema("devmessages")),fill=(template,values)=>template.replace(/\{(\w+)\}/g,(_,key)=>String(values[key]??""));
async function send(to,body,tenant){const token=tenant?.whatsapp?.accessToken?decryptSecret(tenant.whatsapp.accessToken):process.env.WHATSAPP_CLOUD_API_TOKEN,phoneId=tenant?.whatsapp?.phoneNumberId||process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!phoneId){await DevMessage.create({to,body,source:"worker",sentAt:new Date()});return console.log(`[WhatsApp dev] ${to}: ${body}`)}const response=await fetch(`https://graph.facebook.com/v25.0/${phoneId}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to,type:"text",text:{body}})});if(!response.ok)throw new Error(await response.text())}
export async function run(today=new Date()){await mongoose.connect(process.env.MONGODB_URI);const month=today.getMonth()+1,year=today.getFullYear(),[tenants,students]=await Promise.all([Tenant.find().lean(),Student.find().lean()]),active=students.filter(s=>s.status==="active"),tenantMap=new Map(tenants.map(t=>[String(t._id),t])),studentMap=new Map(students.map(s=>[String(s._id),s]));
if(active.length)await Fee.bulkWrite(active.map(student=>{const tenant=tenantMap.get(String(student.tenantId));return{updateOne:{filter:{tenantId:student.tenantId,studentId:student._id,month,year},update:{$setOnInsert:{amount:student.monthlyFee,dueDate:new Date(year,month-1,tenant.feeDueDay),status:"pending",remindersSent:[]}},upsert:true}}}));
for(const fee of await Fee.find({status:{$in:["pending","overdue"]}}).lean()){const type=reminderType(fee,today);if(!type)continue;const start=new Date(today);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const claimed=await Fee.findOneAndUpdate({_id:fee._id,remindersSent:{$not:{$elemMatch:{type,sentAt:{$gte:start,$lt:end}}}}},{$push:{remindersSent:{type,sentAt:today}},...(type==="overdue"?{$set:{status:"overdue"}}:{})});if(!claimed)continue;const tenant=tenantMap.get(String(fee.tenantId)),student=studentMap.get(String(fee.studentId));if(!tenant||!student){await Fee.updateOne({_id:fee._id},{$pull:{remindersSent:{type,sentAt:today}}});continue}const upiLink=tenant.upiId?`upi://pay?pa=${encodeURIComponent(tenant.upiId)}&am=${fee.amount}`:"";try{await send(student.parentPhone,fill(tenant.messageTemplates[type],{studentName:student.name,parentName:"",amount:fee.amount,dueDate:new Date(fee.dueDate).toLocaleDateString("en-IN"),upiLink}),tenant)}catch(error){await Fee.updateOne({_id:fee._id},{$pull:{remindersSent:{type,sentAt:today}}});throw error}}
for(const fee of await Fee.find({status:"paid",receiptSentAt:{$exists:false}}).limit(100).lean()){const tenant=tenantMap.get(String(fee.tenantId)),student=studentMap.get(String(fee.studentId));if(!tenant||!student)continue;try{await send(student.parentPhone,fill(tenant.messageTemplates.receipt,{studentName:student.name,amount:fee.amount}),tenant);await Fee.updateOne({_id:fee._id,receiptSentAt:{$exists:false}},{receiptSentAt:today,$unset:{receiptError:1}})}catch(error){await Fee.updateOne({_id:fee._id},{receiptError:error instanceof Error?error.message:"Send failed"})}}
if(today.getDate()===1)for(const tenant of tenants){const key=`${year}-${month}`,claimed=await Tenant.findOneAndUpdate({_id:tenant._id,lastSummary:{$ne:key}},{lastSummary:key});if(!claimed)continue;const monthly=await Fee.find({tenantId:tenant._id,month,year}).lean();try{await send(tenant.ownerPhone,`${tenant.tuitionName}: ₹${monthly.filter(f=>f.status==="paid").reduce((n,f)=>n+f.amount,0)} collected, ${monthly.filter(f=>f.status!=="paid").length} pending this month.`,tenant)}catch(error){await Tenant.updateOne({_id:tenant._id,lastSummary:key},{$unset:{lastSummary:1}});throw error}}}
cron.schedule("0 8 * * *",()=>run().catch(console.error));
