import Link from "next/link";
import { Calendar, CheckCircle2, ChevronRight, IndianRupee, Settings, User, Users } from "lucide-react";
import { ConfirmForm } from "@/app/components";
import { db } from "@/lib/db";
import { FeeRecord, PendingSubmission, Student, Tenant } from "@/lib/models";
import { session } from "@/lib/auth";

export default async function Dashboard(){
  await db();
  const auth=(await session())!,tenant=await Tenant.findById(auth.tenantId),now=new Date(),month=now.getMonth()+1,year=now.getFullYear(),cutoff=new Date(year,now.getMonth(),now.getDate()+2,23,59,59);
  const [count,fees,requests]=await Promise.all([Student.countDocuments({tenantId:auth.tenantId,status:"active"}),FeeRecord.find({tenantId:auth.tenantId,month,year}).populate("studentId").lean(),PendingSubmission.countDocuments({tenantId:auth.tenantId,status:"pending"})]);
  const pending=fees.filter((f:any)=>f.status!=="paid"),paid=fees.filter((f:any)=>f.status==="paid"),due=pending.filter((f:any)=>new Date(f.dueDate)<=cutoff),sum=(rows:any[])=>rows.reduce((n,f)=>n+f.amount,0).toLocaleString("en-IN");
  return <>
    <header className="rounded-b-[2.5rem] bg-gradient-to-br from-amber-500 to-orange-500 p-6 text-white shadow-xl shadow-orange-500/10">
      <div className="flex items-center justify-between"><Link href="/settings" className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full border border-white/20 bg-white/20 text-lg font-bold backdrop-blur-md">{tenant.tuitionName[0].toUpperCase()}</div><div><h2 className="text-xs font-medium text-amber-50">Hello, Teacher!</h2><h1 className="max-w-[190px] truncate text-lg font-bold">{tenant.tuitionName}</h1></div></Link><Link href="/settings" className="flex h-10 w-10 items-center justify-center rounded-full bg-white/10 backdrop-blur-md transition hover:bg-white/20"><Settings className="h-5 w-5"/></Link></div>
      <div className="mt-6 grid grid-cols-3 gap-2 rounded-3xl bg-white p-5 text-slate-900 shadow-lg shadow-slate-900/5"><div className="border-r border-slate-100 text-center"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Total Students</p><p className="mt-1 text-xl font-extrabold text-slate-800">{count}</p><p className="mt-0.5 text-[9px] text-slate-400">Active</p></div><div className="border-r border-slate-100 text-center"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Fees Collected</p><p className="mt-1 text-xl font-extrabold text-emerald-600">₹{sum(paid)}</p><p className="mt-0.5 text-[9px] font-medium text-emerald-500">Collected</p></div><div className="text-center"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Pending Fees</p><p className="mt-1 text-xl font-extrabold text-rose-500">₹{sum(pending)}</p><p className="mt-0.5 text-[9px] font-medium text-rose-400">Pending</p></div></div>
    </header>
    <div className="flex flex-col gap-4 p-4 pb-28">
      {requests>0&&<Link href="/enrollment-requests" className="flex items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 p-4 transition hover:bg-amber-100"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-amber-500 text-white"><User className="h-5 w-5"/></div><div><h4 className="text-sm font-bold text-amber-900">{requests} new {requests===1?"child wants":"children want"} admission!</h4><p className="text-xs text-amber-700">Parents filled the form using your QR/link.</p></div></div><ChevronRight className="h-5 w-5 text-amber-600"/></Link>}
      <div className="flex items-center justify-between rounded-2xl border border-slate-100 bg-white px-4 py-3"><span className="text-xs font-semibold text-slate-500">Account Month</span><span className="text-sm font-bold text-orange-500">{now.toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</span></div>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><CheckCircle2 className="mb-2 h-5 w-5 text-emerald-600"/><p className="text-xs font-bold text-emerald-800">Collected</p><p className="mt-1 text-lg font-extrabold text-emerald-700">₹{sum(paid)}</p></div><div className="rounded-2xl border border-rose-100 bg-rose-50 p-4"><IndianRupee className="mb-2 h-5 w-5 text-rose-500"/><p className="text-xs font-bold text-rose-800">Pending</p><p className="mt-1 text-lg font-extrabold text-rose-600">₹{sum(pending)}</p></div><div className="rounded-2xl border border-amber-100 bg-amber-50 p-4"><Calendar className="mb-2 h-5 w-5 text-amber-600"/><p className="text-xs font-bold text-amber-800">Due Soon</p><p className="mt-1 text-lg font-extrabold text-amber-700">{due.length}</p></div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><Users className="mb-2 h-5 w-5 text-blue-600"/><p className="text-xs font-bold text-blue-800">Total Students</p><p className="mt-1 text-lg font-extrabold text-blue-700">{count}</p></div></div>
      <section><h2 className="mb-3 text-sm font-bold text-slate-800">Fees requiring attention</h2><div className="space-y-3">{due.length?due.map((fee:any)=><article key={String(fee._id)} className="rounded-2xl border border-slate-100 bg-white p-3.5 shadow-sm"><div className="mb-3 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-orange-500 text-sm font-bold text-white">{fee.studentId?.name?.[0]}</div><div className="min-w-0 flex-1"><h4 className="truncate font-bold text-slate-800">{fee.studentId?.name}</h4><p className="text-xs text-slate-400">{fee.studentId?.class} • Due {new Date(fee.dueDate).toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</p></div><b className="text-rose-500">₹{fee.amount.toLocaleString("en-IN")}</b></div><ConfirmForm action="/api/fees/mark-paid" message={`Mark ₹${fee.amount} as paid for ${fee.studentId?.name}?`}><input type="hidden" name="id" value={String(fee._id)}/><button className="w-full rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 py-2.5 text-xs font-bold text-white shadow-md shadow-orange-500/10">Mark Fee Paid</button></ConfirmForm></article>):<div className="rounded-3xl border border-slate-100 bg-white p-8 text-center text-xs text-slate-400">All caught up. No fees are currently due.</div>}</div></section>
      <Link href="/students/add" className="fixed bottom-[82px] right-4 z-10 flex h-11 w-11 items-center justify-center rounded-full bg-orange-500 text-2xl text-white shadow-lg shadow-orange-500/30">+</Link>
    </div>
  </>;
}
