"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";

const icons: Record<string, React.ReactNode> = {
  home: <><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></>,
  users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
  settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.1A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.15.37.36.7.6 1 .3.3.7.46 1.1.4h.1v4h-.1A1.7 1.7 0 0 0 19.4 15Z"/></>
};
export function Icon({name,size=20}:{name:string,size?:number}) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{icons[name]}</svg> }
export function BottomNav(){const path=usePathname(),items=[["/dashboard","home","Home"],["/students","users","Students"],["/settings","settings","Settings"]];return <nav className="nav">{items.map(([href,icon,label])=><Link key={href} className={path.startsWith(href)?"active":""} href={href}><Icon name={icon}/><span>{label}</span></Link>)}</nav>}
export function ConfirmForm({action,message,children}:{action:string;message:string;children:React.ReactNode}){return <form action={action} method="post" onSubmit={(e:FormEvent)=>{if(!confirm(message))e.preventDefault()}}>{children}</form>}
export function LoginForm(){const[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[sent,setSent]=useState(false),[newUser,setNewUser]=useState(false),[name,setName]=useState(""),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false);useEffect(()=>{if(!seconds)return;const timer=setTimeout(()=>setSeconds(seconds-1),1000);return()=>clearTimeout(timer)},[seconds]);async function send(){setBusy(true);const r=await fetch("/api/auth/otp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone})}),data=await r.json();setBusy(false);if(!r.ok)return alert(data.error);setOtp(data.otp);setNewUser(data.newUser);setSent(true);setSeconds(30)}async function verify(){setBusy(true);const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,otp,tuitionName:name})});setBusy(false);if(r.ok)location.href="/dashboard";else alert((await r.json()).error)}return <main className="login-screen"><div className="brand-mark">₹</div><h1>Tuition Fee Manager</h1><p className="muted">Digital record-keeping for tuition fees and students</p><section className="login-card">{!sent?<><label className="field upper">Enter your mobile number<div className="phone-input"><span>+91</span><input inputMode="numeric" maxLength={10} placeholder="98765 43210" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,""))}/></div></label><small className="hint">Use your registered owner phone number</small></>:<><div className="otp-note">We sent a 6-digit OTP to +91 {phone}</div>{newUser&&<label className="field upper">Tuition classes name<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label className="field upper">Enter 6-digit OTP<input className="otp-input" inputMode="numeric" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))}/></label></>}<button className="btn full" onClick={sent?verify:send} disabled={busy||(sent?otp.length!==6||newUser&&!name.trim():phone.length!==10)}>{busy?"Please wait…":sent?"Verify & Login":"Next  ›"}</button>{sent&&<div className="login-links"><button className="link" onClick={()=>setSent(false)}>Change number</button><button className="link" disabled={seconds>0||busy} onClick={send}>Resend{seconds>0?` in ${seconds}s`:" OTP"}</button></div>}</section><small className="secure">Secure & Reliable · Data is saved securely in cloud</small></main>}
