"use client";
import { Camera, GraduationCap, UserRound } from "lucide-react";
import { ChangeEvent,useState } from "react";

const avatars=["blue","orange","purple","green"] as const;
const colors={blue:"bg-sky-500",orange:"bg-orange-500",purple:"bg-violet-500",green:"bg-emerald-500"};
export function ProfileForm({tenant}:{tenant:{ownerName?:string;tuitionName:string;ownerPhone:string;ownerAvatar?:string;ownerPhotoUrl?:string}}){
  const[avatar,setAvatar]=useState(tenant.ownerAvatar||"orange"),[photo,setPhoto]=useState(tenant.ownerPhotoUrl||""),[error,setError]=useState("");
  function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>1_000_000){setError("Please choose an image smaller than 1 MB");return}const reader=new FileReader();reader.onload=()=>{setPhoto(String(reader.result));setError("")};reader.readAsDataURL(file)}
  return <form action="/api/profile" method="post" className="space-y-4"><section className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><p className="mb-5 text-xs font-bold uppercase tracking-wider text-slate-500">Teacher Profile</p><div className="flex flex-col items-center"><label className="relative cursor-pointer"><span className={`flex h-20 w-20 items-center justify-center overflow-hidden rounded-full text-2xl font-bold text-white shadow-lg ${colors[avatar as keyof typeof colors]||colors.orange}`}>{photo?<img src={photo} alt="Profile" className="h-full w-full object-cover"/>:(tenant.ownerName||tenant.tuitionName)[0].toUpperCase()}</span><span className="absolute bottom-0 right-0 flex h-7 w-7 items-center justify-center rounded-full bg-slate-700 text-white"><Camera className="h-3.5 w-3.5"/></span><input className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><b className="mt-2 text-xs text-slate-600">Upload Profile Picture</b><small className="text-[10px] text-slate-400">JPG, PNG or WebP · max 1 MB</small>{error&&<small className="mt-1 text-rose-500">{error}</small>}<p className="my-4 text-[10px] font-bold uppercase tracking-wider text-slate-400">Or choose an avatar</p><div className="flex gap-3">{avatars.map((value,i)=><button key={value} type="button" onClick={()=>{setAvatar(value);setPhoto("")}} className={`flex h-12 w-12 items-center justify-center rounded-full text-white transition ${colors[value]} ${avatar===value&&!photo?"ring-4 ring-orange-100":""}`}>{i===2?<GraduationCap className="h-6 w-6"/>:<UserRound className="h-6 w-6"/>}</button>)}</div></div><input type="hidden" name="ownerAvatar" value={avatar}/><input type="hidden" name="ownerPhotoUrl" value={photo}/><div className="mt-6 space-y-3"><label className="block space-y-1 text-xs font-semibold text-slate-500">Teacher&apos;s Name<input className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-orange-500" name="ownerName" defaultValue={tenant.ownerName} placeholder="e.g. Sunil Gujar" required/></label><label className="block space-y-1 text-xs font-semibold text-slate-500">Tuition / Academy Name<input className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-orange-500" name="tuitionName" defaultValue={tenant.tuitionName} required/></label><label className="block space-y-1 text-xs font-semibold text-slate-500">Registered Mobile Number (Read-only)<input className="w-full rounded-2xl border border-slate-200 bg-slate-100 px-4 py-3 text-sm text-slate-400" value={`+91 ${tenant.ownerPhone}`} readOnly/></label><button className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 text-sm font-bold text-white shadow-md shadow-orange-500/20">Update Profile</button></div></section></form>;
}
